// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iugsvpkobxxeycjwlkgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1Z3N2cGtvYnh4ZXljandsa2d6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NjEwNzIsImV4cCI6MjA3MDAzNzA3Mn0.kvAKOK_Tgu4yRoGuvDAg_z_07sgmM3sTFLrRghxnxBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});